# Generated by Django 5.1.2 on 2024-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0002_alter_file_file_alter_file_user_folder_file_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
